services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "28080:28080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - kroki

  kroki:
    image: yuzutech/kroki:latest
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
